/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projetoac1calculadoraviabilidade;

/**
 *
 * @author Aluno
 */
public class CalculadoraViabilidadeFinanceira extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraViabilidadeFinanceira
     */
    public CalculadoraViabilidadeFinanceira() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        txtRetorno3 = new javax.swing.JTextArea();
        lblTitulo = new javax.swing.JLabel();
        lblSubTitulo = new javax.swing.JLabel();
        lblQtdPedidosApp = new javax.swing.JLabel();
        txtQtdPedidosApp = new javax.swing.JTextField();
        lblTicketMedio = new javax.swing.JLabel();
        txtTicketMedio = new javax.swing.JTextField();
        lblTempoOff = new javax.swing.JLabel();
        txtTempoOff = new javax.swing.JTextField();
        btnCalculo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRetorno1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRetorno2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtRetornomes = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtretornoano = new javax.swing.JTextArea();

        txtRetorno3.setColumns(20);
        txtRetorno3.setRows(5);
        jScrollPane3.setViewportView(txtRetorno3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Viabilidade do Sistema MNBurger");

        lblSubTitulo.setText("Cenário de pedidos via Aplicativos (Ifood)");

        lblQtdPedidosApp.setText("Informe a quantidade de pedidos por hora");

        lblTicketMedio.setText("Iinforme o ticket Médio dos pedidos");

        lblTempoOff.setText("Informe o tempo de indisponibilidade (em minutos) do seu sistema  (offline) nas últimas 24hrs");

        btnCalculo.setText("Calcule o tamanho da oportunidade que perdeu por estar offline");
        btnCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculoActionPerformed(evt);
            }
        });

        txtRetorno1.setColumns(20);
        txtRetorno1.setRows(5);
        jScrollPane1.setViewportView(txtRetorno1);

        txtRetorno2.setColumns(20);
        txtRetorno2.setRows(5);
        jScrollPane2.setViewportView(txtRetorno2);

        txtRetornomes.setColumns(20);
        txtRetornomes.setRows(5);
        jScrollPane4.setViewportView(txtRetornomes);

        txtretornoano.setColumns(20);
        txtretornoano.setRows(5);
        jScrollPane5.setViewportView(txtretornoano);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSubTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQtdPedidosApp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo)
                            .addComponent(txtQtdPedidosApp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTicketMedio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTicketMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCalculo)
                            .addComponent(lblTempoOff))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTempoOff, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblSubTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdPedidosApp)
                    .addComponent(txtQtdPedidosApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTicketMedio)
                    .addComponent(txtTicketMedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTempoOff)
                    .addComponent(txtTempoOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculoActionPerformed
//ao clicar no btnCalculo deve ser fazer as contas 
// quantidade de pedidos por hora /por 60 (minuto) = X
// X * ticket médio = y
//tempo off * y = txtPerda1
//txtPerda1 * y

String pedidosApp = txtQtdPedidosApp.getText();
Double qtdPedidosApp = Double.valueOf(pedidosApp);

String ticketMed = txtTicketMedio.getText();
Double vlTicketMed = Double.valueOf(ticketMed);

String tmpOff = txtTempoOff.getText();
Double tempoOff = Double.valueOf(tmpOff);

Double  resul1, resul2;

Double resul3, resul4, resul5, resul6, resul7, resul8, resul9;

Integer minutosdodia;

resul1 = (qtdPedidosApp / 60) * tempoOff;

resul2 = (resul1 * vlTicketMed);

resul3 = (resul1 * qtdPedidosApp) / 100 ;

minutosdodia = 60 * 24;

resul8 = resul1 * minutosdodia;

resul9 = resul2 * minutosdodia;

resul4 = resul8 * 30 ;

resul5 = (resul9 * 30) / 100;

resul6 = resul4 * 365;

resul7 = (resul5 * 365) / 100;

String retornoum = "";

String retornodois = "";

String retornomes = "";

String retornoano = "";


retornoum = String.format("Você perdeu a oportunidade conquistar %.2f pedidos e faturar %.2f reais", resul1,resul2);
txtRetorno1.setText(retornoum);

retornodois = String.format ("Monitorando o seu sistema com a MNBURGUER, reduzindo indisponibilidades, você poderia ter um acréscimo de %.2f porcento nos seus pedidos.", resul3);
txtRetorno2.setText(retornodois);

retornomes = String.format ("Sua potencial perda é de %.2f pedidos ao mes que reflete em  %.2f por cento a mais no mês", resul4, resul5);
txtRetornomes.setText(retornomes);

retornoano = String.format ("Sua potencial perda é de %.2f pedidos ao ano que reflete em %.2f por cento a mais no ano", resul5, resul7);
txtretornoano.setText (retornoano);














    }//GEN-LAST:event_btnCalculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraViabilidadeFinanceira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraViabilidadeFinanceira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraViabilidadeFinanceira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraViabilidadeFinanceira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraViabilidadeFinanceira().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblQtdPedidosApp;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblTempoOff;
    private javax.swing.JLabel lblTicketMedio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtQtdPedidosApp;
    private javax.swing.JTextArea txtRetorno1;
    private javax.swing.JTextArea txtRetorno2;
    private javax.swing.JTextArea txtRetorno3;
    private javax.swing.JTextArea txtRetornomes;
    private javax.swing.JTextField txtTempoOff;
    private javax.swing.JTextField txtTicketMedio;
    private javax.swing.JTextArea txtretornoano;
    // End of variables declaration//GEN-END:variables
}
